events { worker_connections 1024; }

http {
    upstream rpc_backend {
        server stg-node:8545;
    }

    server {
        listen 80;
        server_name rpc.quorumstate.international;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name rpc.quorumstate.international;

        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://rpc_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
